# Generated by Django 5.0.7 on 2024-07-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenapp', '0002_rename_product_ordendia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordendia',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='ordendia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordendia',
            name='name',
            field=models.CharField(default='Default Name', max_length=50),
        ),
        migrations.AddField(
            model_name='ordendia',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ordendia',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='foto'),
        ),
        migrations.AlterModelTable(
            name='ordendia',
            table='Orden',
        ),
    ]
