# Generated by Django 5.0.7 on 2024-07-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenapp', '0003_alter_ordendia_options_ordendia_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendia',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
