# Generated by Django 5.0.7 on 2024-07-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenapp', '0004_alter_ordendia_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordendia',
            table='orden',
        ),
    ]
